### ISSUE TITLE
How can I highlight an area of the LiteMol protein structure programmatically?

### ISSUE THREAD

**Issue by panoromix** [davidhoksza/MolArt#10]
Same as the type of colored highlights applied on the LiteMol protein structure when clicking a position on the ProtVista panel.

**Comment by davidhoksza** [comment]
You can access the LiteMol plugin via `molart_instance.getLmController().getPlugin()`. Then you can highlight things exactly the same way as you would in LiteMol.

BTW, similarly, you can acces the ProtVista plugin via `molstar.getPvController().getPlugin()`.

**Comment by panoromix** [comment]
Excellent thanks very much I'll try that
