### ISSUE TITLE
Official example fails with "Can't access property "charAt", t.alternativeSequence is undefined"

### ISSUE THREAD

**Issue by panoromix** [davidhoksza/MolArt#17]
Visualization cannot load. When it does, all variants are displayed as black circles on the ProtVista panel and inside the console the error appears:

"Can't access property "charAt", t.alternativeSequence is undefined"

I thought this was only on my local test instance but when I check your example and try to load up the gene symbol "P48029 | SC6A8_HUMAN | reviewed" I get the same result at:

https://davidhoksza.github.io/MolArt/examples/web/index.html

**Comment by panoromix** [comment]
Not sure if this helps but it looks like proteins without antigen values will have this error.

For example, loading from this source:

[https://www.ebi.ac.uk/proteins/api/antigen/O00241](https://www.ebi.ac.uk/proteins/api/antigen/O00241)

Returns antigen values as JSON data and the visualization loads just fine.

However from this source:

[https://www.ebi.ac.uk/proteins/api/antigen/P01889](https://www.ebi.ac.uk/proteins/api/antigen/P01889)

Returns no values and the visualization throws the error mentioned above.

**Comment by davidhoksza** [comment]
I had just a brief look and my guess is that the API which is used changed. I will solve the problem over the weekend and will let you know once it's ready. Thanks for reporting this!

**Comment by davidhoksza** [comment]
Should be fixed now. The problem was indeed in the Proteins API because they changed the way they encode the predicted effect of variations.
