### ISSUE TITLE
jQuery.Deferred exception: t.dropdown is not a function

### ISSUE THREAD

**Issue by panoromix** [davidhoksza/MolArt#18]
On the official example found at:
https://davidhoksza.github.io/MolArt/examples/web/index.html

When searching for gene symbol 'SLC6A8' and selecting the first entry in the table, 'P48029', the visualization hangs with a loading GIF spinning on screen while the browser console shows the following error:

"jQuery.Deferred exception: t.dropdown is not a function"

This behavior is also present on an instance I am running on one of my own web servers after installing the updated library files as of the latest commit yesterday (10/11/20).

**Comment by davidhoksza** [comment]
Fixed now. The problem was conflicting import of jQuery object with SemanticsUI. Not sure what changed in the updated dependencies between the versions, but the error should be gone now.
